; highlights.scm

; Keywords
"ACTION"        @keyword
"ASSUME"        @keyword
"ASSUMPTION"    @keyword
"AXIOM"         @keyword
"BY"            @keyword
"CASE"          @keyword
"CHOOSE"        @keyword
"CONSTANT"      @keyword
"CONSTANTS"     @keyword
"COROLLARY"     @keyword
"DEF"           @keyword
"DEFINE"        @keyword
"DEFS"          @keyword
"DOMAIN"        @keyword
"ELSE"          @keyword
"ENABLED"       @keyword
"EXCEPT"        @keyword
"EXTENDS"       @keyword
"HAVE"          @keyword
"HIDE"          @keyword
"IF"            @keyword
"IN"            @keyword
"INSTANCE"      @keyword
"LAMBDA"        @keyword
"LEMMA"         @keyword
"LET"           @keyword
"LOCAL"         @keyword
"MODULE"        @keyword
"NEW"           @keyword
"OBVIOUS"       @keyword
"OMITTED"       @keyword
"ONLY"          @keyword
"OTHER"         @keyword
"PICK"          @keyword
"PROOF"         @keyword
"PROPOSITION"   @keyword
"PROVE"         @keyword
"QED"           @keyword
"RECURSIVE"     @keyword
"SF_"           @keyword
"STATE"         @keyword
"SUBSET"        @keyword
"SUFFICES"      @keyword
"TAKE"          @keyword
"TEMPORAL"      @keyword
"THEN"          @keyword
"THEOREM"       @keyword
"UNCHANGED"     @keyword
"UNION"         @keyword
"USE"           @keyword
"VARIABLE"      @keyword
"VARIABLES"     @keyword
"WF_"           @keyword
"WITH"          @keyword
"WITNESS"       @keyword

; Literals
(number) @number
(string) @string
(boolean) @constant.builtin
(primitive_value_set) @type

